version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: python run1.py

  mapping-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: python mapping.py

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
  flower:
    build: .
    command: /bin/sh -c "sleep 5 && celery --broker=redis://redis:6379/0 flower"
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app
    working_dir: /app


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"